Rendering the buffer zone during digitization
nextgis/qgis_digitizr pull request #13
Opened 2024-06-17 14:26 UTC by RemeshevskiyValeriy

2024-06-18 03:31 UTC, ivanbarsukov requested changes

2024-06-18 03:31 UTC, ivanbarsukov commented on src/qgis_digitizr/qgsmaptooladdlinebuffer.py
> +        self.rb = QgsRubberBand(self.canvas(), QgsWkbTypes.PolygonGeometry)
Давай уберем в private всё, что не должно быть в интерфейсе инструмента

2024-06-18 03:31 UTC, ivanbarsukov commented on src/qgis_digitizr/qgsmaptooladdlinebuffer.py
> +        self.feat_temp = QgsFeature()
Думаю, тут можно было обойтись QgsGeometry?

2024-06-18 03:31 UTC, ivanbarsukov commented on src/qgis_digitizr/qgsmaptooladdlinebuffer.py
> +    def cadCanvasMoveEvent(self, event: Optional[QgsMapMouseEvent]) -> None:
Сигнатура с базовом классе говорит о том, что тут не `Optional`

2024-06-18 03:31 UTC, ivanbarsukov commented on src/qgis_digitizr/qgsmaptooladdlinebuffer.py
> +        temp_buffer_geometry = temp_line_geometry.buffer(
Давай уберем создание буфера в отдельный метод

2024-06-18 03:31 UTC, ivanbarsukov commented on src/qgis_digitizr/qgsmaptooladdlinebuffer.py
> +        temp_line_wkt = self.captureCurve().curveToLine().asWkt()
Кажется, тут должлно быть достаточно  `QgsGeometry(self.captureCurve().curveToLine())`

2024-06-20 16:40 UTC, ann-who requested changes

2024-06-20 16:40 UTC, ann-who commented on src/digitizr/qgsmaptooladdlinebuffer.py
> +        self.last_position = QgsPoint(event.mapPoint())
Сохраняешь в переменную чтобы перерисовать последнее состояние до покидания канваса при изменении настроек? Тут, кстати, тоже лучше убрать в private

2024-06-20 16:40 UTC, ann-who commented on src/digitizr/qgsmaptooladdlinebuffer.py
> +        self.last_position = QgsPoint(event.mapPoint())
Еще выглядит так, что можно сохранить эту точку и вызвать `__repainting_rubberband`

2024-06-20 16:40 UTC, ann-who commented on src/digitizr/qgsmaptooladdlinebuffer.py
> +    def __repainting_rubberband(self):
Для названий методов лучше использовать глаголы: `repaint`

2024-06-21 13:52 UTC, merged